export const RESET_MESSAGE = "RESET_MESSAGE";

export const LOGIN_PROGRESS = 'LOGIN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_PROGRESS = "LOGOUT_PROGRESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const ADD_PROJECT_PROGRESS = "ADD_PROJECT_PROGRESS";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_FAILURE = "ADD_PROJECT_FAILURE";

export const GET_PROJECT_LIST_PROGRESS = "GET_PROJECT_LIST_PROGRESS";
export const GET_PROJECT_LIST_SUCCESS = "GET_PROJECT_LIST_SUCCESS";
export const GET_PROJECT_LIST_FAILURE = "GET_PROJECT_LIST_FAILURE";

export const EDIT_PROJECT_STATUS_PROGRESS = "EDIT_PROJECT_STATUS_PROGRESS";
export const EDIT_PROJECT_STATUS_SUCCESS = "EDIT_PROJECT_STATUS_SUCCESS";
export const EDIT_PROJECT_STATUS_FAILURE = "EDIT_PROJECT_STATUS_FAILURE";

export const GET_DASHBOARD_TOTAL_RECORDS_PROGRESS = "GET_DASHBOARD_TOTAL_RECORDS_PROGRESS";
export const GET_DASHBOARD_TOTAL_RECORDS_SUCCESS = "GET_DASHBOARD_TOTAL_RECORDS_SUCCESS";
export const GET_DASHBOARD_TOTAL_RECORDS_FAILURE = "GET_DASHBOARD_TOTAL_RECORDS_FAILURE";

export const GET_DEPT_WISE_SUCCESS_PERCENTAGE_PROGRESS = "GET_DEPT_WISE_SUCCESS_PERCENTAGE_PROGRESS";
export const GET_DEPT_WISE_SUCCESS_PERCENTAGE_SUCCESS = "GET_DEPT_WISE_SUCCESS_PERCENTAGE_SUCCESS";
export const GET_DEPT_WISE_SUCCESS_PERCENTAGE_FAILURE = "GET_DEPT_WISE_SUCCESS_PERCENTAGE_FAILURE";

export const GET_DIVISION_WISE_CHART_PROGRESS = "GET_DIVISION_WISE_CHART_PROGRESS";
export const GET_DIVISION_WISE_CHART_SUCCESS = "GET_DIVISION_WISE_CHART_SUCCESS";
export const GET_DIVISION_WISE_CHART_FAILURE = "GET_DIVISION_WISE_CHART_FAILURE";